FROM python:3.11

RUN mkdir /app
WORKDIR /app
COPY . .

RUN pip install --upgrade pip
RUN pip install .

ENTRYPOINT ["/bin/bash", "-c", "run-dashboard --api-type $API_TYPE --host $HOST --port $PORT"]
