# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import mops.backend.apps.grpc.server_pb2 as server__pb2

GRPC_GENERATED_VERSION = "1.68.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + f" but the generated code in server_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class MopsAppStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Train = channel.unary_unary(
            "/MopsApp/Train",
            request_serializer=server__pb2.TrainInput.SerializeToString,
            response_deserializer=server__pb2.TrainOutput.FromString,
            _registered_method=True,
        )
        self.Predict = channel.unary_unary(
            "/MopsApp/Predict",
            request_serializer=server__pb2.PredictInput.SerializeToString,
            response_deserializer=server__pb2.PredictOutput.FromString,
            _registered_method=True,
        )
        self.Retrain = channel.unary_unary(
            "/MopsApp/Retrain",
            request_serializer=server__pb2.RetrainInput.SerializeToString,
            response_deserializer=server__pb2.RetrainOutput.FromString,
            _registered_method=True,
        )
        self.DeleteModel = channel.unary_unary(
            "/MopsApp/DeleteModel",
            request_serializer=server__pb2.DeleteModelInput.SerializeToString,
            response_deserializer=server__pb2.DeleteModelOutput.FromString,
            _registered_method=True,
        )
        self.List_trained_models = channel.unary_unary(
            "/MopsApp/List_trained_models",
            request_serializer=server__pb2.Empty1.SerializeToString,
            response_deserializer=server__pb2.ModelList.FromString,
            _registered_method=True,
        )
        self.List_available_models = channel.unary_unary(
            "/MopsApp/List_available_models",
            request_serializer=server__pb2.Empty2.SerializeToString,
            response_deserializer=server__pb2.AvailableModels.FromString,
            _registered_method=True,
        )
        self.List_available_datasets = channel.unary_unary(
            "/MopsApp/List_available_datasets",
            request_serializer=server__pb2.Empty3.SerializeToString,
            response_deserializer=server__pb2.AvailableDatasets.FromString,
            _registered_method=True,
        )
        self.GetDataset = channel.unary_unary(
            "/MopsApp/GetDataset",
            request_serializer=server__pb2.GetDataName.SerializeToString,
            response_deserializer=server__pb2.Dataset.FromString,
            _registered_method=True,
        )
        self.GetModelsDataset = channel.unary_unary(
            "/MopsApp/GetModelsDataset",
            request_serializer=server__pb2.ModelID.SerializeToString,
            response_deserializer=server__pb2.DatasetName.FromString,
            _registered_method=True,
        )
        self.PredictProba = channel.unary_unary(
            "/MopsApp/PredictProba",
            request_serializer=server__pb2.PredictProbaInput.SerializeToString,
            response_deserializer=server__pb2.PredictProbaOutput.FromString,
            _registered_method=True,
        )
        self.HealthCheck = channel.unary_unary(
            "/MopsApp/HealthCheck",
            request_serializer=server__pb2.Empty4.SerializeToString,
            response_deserializer=server__pb2.ServerStatus.FromString,
            _registered_method=True,
        )
        self.ShowDocString = channel.unary_unary(
            "/MopsApp/ShowDocString",
            request_serializer=server__pb2.Model.SerializeToString,
            response_deserializer=server__pb2.ModelDocString.FromString,
            _registered_method=True,
        )
        self.CreateDataset = channel.unary_unary(
            "/MopsApp/CreateDataset",
            request_serializer=server__pb2.UserDataset.SerializeToString,
            response_deserializer=server__pb2.CreateDatasetOutput.FromString,
            _registered_method=True,
        )
        self.DeleteDataset = channel.unary_unary(
            "/MopsApp/DeleteDataset",
            request_serializer=server__pb2.DeleteDatasetInput.SerializeToString,
            response_deserializer=server__pb2.DeleteDatasetOutput.FromString,
            _registered_method=True,
        )
        self.List_user_datasets = channel.unary_unary(
            "/MopsApp/List_user_datasets",
            request_serializer=server__pb2.UserDatasetsInput.SerializeToString,
            response_deserializer=server__pb2.UserDatasetsOutput.FromString,
            _registered_method=True,
        )


class MopsAppServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Train(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Predict(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Retrain(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def DeleteModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def List_trained_models(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def List_available_models(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def List_available_datasets(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetDataset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetModelsDataset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def PredictProba(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def HealthCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ShowDocString(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def CreateDataset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def DeleteDataset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def List_user_datasets(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_MopsAppServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Train": grpc.unary_unary_rpc_method_handler(
            servicer.Train,
            request_deserializer=server__pb2.TrainInput.FromString,
            response_serializer=server__pb2.TrainOutput.SerializeToString,
        ),
        "Predict": grpc.unary_unary_rpc_method_handler(
            servicer.Predict,
            request_deserializer=server__pb2.PredictInput.FromString,
            response_serializer=server__pb2.PredictOutput.SerializeToString,
        ),
        "Retrain": grpc.unary_unary_rpc_method_handler(
            servicer.Retrain,
            request_deserializer=server__pb2.RetrainInput.FromString,
            response_serializer=server__pb2.RetrainOutput.SerializeToString,
        ),
        "DeleteModel": grpc.unary_unary_rpc_method_handler(
            servicer.DeleteModel,
            request_deserializer=server__pb2.DeleteModelInput.FromString,
            response_serializer=server__pb2.DeleteModelOutput.SerializeToString,
        ),
        "List_trained_models": grpc.unary_unary_rpc_method_handler(
            servicer.List_trained_models,
            request_deserializer=server__pb2.Empty1.FromString,
            response_serializer=server__pb2.ModelList.SerializeToString,
        ),
        "List_available_models": grpc.unary_unary_rpc_method_handler(
            servicer.List_available_models,
            request_deserializer=server__pb2.Empty2.FromString,
            response_serializer=server__pb2.AvailableModels.SerializeToString,
        ),
        "List_available_datasets": grpc.unary_unary_rpc_method_handler(
            servicer.List_available_datasets,
            request_deserializer=server__pb2.Empty3.FromString,
            response_serializer=server__pb2.AvailableDatasets.SerializeToString,
        ),
        "GetDataset": grpc.unary_unary_rpc_method_handler(
            servicer.GetDataset,
            request_deserializer=server__pb2.GetDataName.FromString,
            response_serializer=server__pb2.Dataset.SerializeToString,
        ),
        "GetModelsDataset": grpc.unary_unary_rpc_method_handler(
            servicer.GetModelsDataset,
            request_deserializer=server__pb2.ModelID.FromString,
            response_serializer=server__pb2.DatasetName.SerializeToString,
        ),
        "PredictProba": grpc.unary_unary_rpc_method_handler(
            servicer.PredictProba,
            request_deserializer=server__pb2.PredictProbaInput.FromString,
            response_serializer=server__pb2.PredictProbaOutput.SerializeToString,
        ),
        "HealthCheck": grpc.unary_unary_rpc_method_handler(
            servicer.HealthCheck,
            request_deserializer=server__pb2.Empty4.FromString,
            response_serializer=server__pb2.ServerStatus.SerializeToString,
        ),
        "ShowDocString": grpc.unary_unary_rpc_method_handler(
            servicer.ShowDocString,
            request_deserializer=server__pb2.Model.FromString,
            response_serializer=server__pb2.ModelDocString.SerializeToString,
        ),
        "CreateDataset": grpc.unary_unary_rpc_method_handler(
            servicer.CreateDataset,
            request_deserializer=server__pb2.UserDataset.FromString,
            response_serializer=server__pb2.CreateDatasetOutput.SerializeToString,
        ),
        "DeleteDataset": grpc.unary_unary_rpc_method_handler(
            servicer.DeleteDataset,
            request_deserializer=server__pb2.DeleteDatasetInput.FromString,
            response_serializer=server__pb2.DeleteDatasetOutput.SerializeToString,
        ),
        "List_user_datasets": grpc.unary_unary_rpc_method_handler(
            servicer.List_user_datasets,
            request_deserializer=server__pb2.UserDatasetsInput.FromString,
            response_serializer=server__pb2.UserDatasetsOutput.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler("MopsApp", rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("MopsApp", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class MopsApp(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Train(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/MopsApp/Train",
            server__pb2.TrainInput.SerializeToString,
            server__pb2.TrainOutput.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Predict(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/MopsApp/Predict",
            server__pb2.PredictInput.SerializeToString,
            server__pb2.PredictOutput.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Retrain(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/MopsApp/Retrain",
            server__pb2.RetrainInput.SerializeToString,
            server__pb2.RetrainOutput.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def DeleteModel(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/MopsApp/DeleteModel",
            server__pb2.DeleteModelInput.SerializeToString,
            server__pb2.DeleteModelOutput.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def List_trained_models(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/MopsApp/List_trained_models",
            server__pb2.Empty1.SerializeToString,
            server__pb2.ModelList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def List_available_models(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/MopsApp/List_available_models",
            server__pb2.Empty2.SerializeToString,
            server__pb2.AvailableModels.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def List_available_datasets(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/MopsApp/List_available_datasets",
            server__pb2.Empty3.SerializeToString,
            server__pb2.AvailableDatasets.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetDataset(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/MopsApp/GetDataset",
            server__pb2.GetDataName.SerializeToString,
            server__pb2.Dataset.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetModelsDataset(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/MopsApp/GetModelsDataset",
            server__pb2.ModelID.SerializeToString,
            server__pb2.DatasetName.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def PredictProba(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/MopsApp/PredictProba",
            server__pb2.PredictProbaInput.SerializeToString,
            server__pb2.PredictProbaOutput.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def HealthCheck(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/MopsApp/HealthCheck",
            server__pb2.Empty4.SerializeToString,
            server__pb2.ServerStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ShowDocString(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/MopsApp/ShowDocString",
            server__pb2.Model.SerializeToString,
            server__pb2.ModelDocString.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def CreateDataset(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/MopsApp/CreateDataset",
            server__pb2.UserDataset.SerializeToString,
            server__pb2.CreateDatasetOutput.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def DeleteDataset(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/MopsApp/DeleteDataset",
            server__pb2.DeleteDatasetInput.SerializeToString,
            server__pb2.DeleteDatasetOutput.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def List_user_datasets(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/MopsApp/List_user_datasets",
            server__pb2.UserDatasetsInput.SerializeToString,
            server__pb2.UserDatasetsOutput.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
